# Generated by Django 3.0.6 on 2020-05-13 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_auto_20200511_1733'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Statistics',
            new_name='HittingStatistics',
        ),
        migrations.AlterModelOptions(
            name='hittingstatistics',
            options={'ordering': ('id',), 'verbose_name_plural': 'Statistics'},
        ),
    ]
