# Generated by Django 3.0.6 on 2020-05-16 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_auto_20200513_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='hittingstatistics',
            name='fTotal',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Fantasy Total'),
        ),
        migrations.AlterField(
            model_name='hittingstatistics',
            name='year',
            field=models.PositiveSmallIntegerField(verbose_name='Year'),
        ),
    ]
