# Generated by Django 3.0.6 on 2020-05-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_auto_20200517_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='hittingstatistics',
            name='fBB',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Fantasy Home Runs'),
        ),
        migrations.AddField(
            model_name='hittingstatistics',
            name='fCS',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Fantasy Home Runs'),
        ),
        migrations.AddField(
            model_name='hittingstatistics',
            name='fGDP',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Fantasy Home Runs'),
        ),
        migrations.AddField(
            model_name='hittingstatistics',
            name='fHBP',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Fantasy Home Runs'),
        ),
        migrations.AddField(
            model_name='hittingstatistics',
            name='fIBB',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Fantasy Home Runs'),
        ),
        migrations.AddField(
            model_name='hittingstatistics',
            name='fOBP',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Fantasy Home Runs'),
        ),
        migrations.AddField(
            model_name='hittingstatistics',
            name='fPA',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Fantasy Home Runs'),
        ),
        migrations.AddField(
            model_name='hittingstatistics',
            name='fSF',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Fantasy Home Runs'),
        ),
        migrations.AddField(
            model_name='hittingstatistics',
            name='fSH',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Fantasy Home Runs'),
        ),
        migrations.AddField(
            model_name='hittingstatistics',
            name='fSLG',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Fantasy Home Runs'),
        ),
        migrations.AddField(
            model_name='hittingstatistics',
            name='fSO',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Fantasy Home Runs'),
        ),
    ]
