# Generated by Django 3.0.6 on 2020-05-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0008_auto_20200517_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='hittingstatistics',
            name='fG',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Fantasy Home Runs'),
        ),
    ]
