# Generated by Django 3.0.6 on 2020-06-19 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0009_hittingstatistics_fg'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hittingstatistics',
            options={'ordering': ('fTotal', 'id'), 'verbose_name_plural': 'Hitting Statistics'},
        ),
        migrations.CreateModel(
            name='PitchingStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Year')),
                ('W', models.SmallIntegerField(blank=True, null=True, verbose_name='Wins')),
                ('L', models.SmallIntegerField(blank=True, null=True, verbose_name='Losses')),
                ('ERA', models.FloatField(blank=True, null=True, verbose_name='Earned Run Average')),
                ('G', models.SmallIntegerField(blank=True, null=True, verbose_name='Games Played')),
                ('GS', models.SmallIntegerField(blank=True, null=True, verbose_name='Games Started')),
                ('CG', models.SmallIntegerField(blank=True, null=True, verbose_name='Complete Games')),
                ('ShO', models.SmallIntegerField(blank=True, null=True, verbose_name='Shutouts')),
                ('SV', models.SmallIntegerField(blank=True, null=True, verbose_name='Saves')),
                ('HLD', models.SmallIntegerField(blank=True, null=True, verbose_name='Holds')),
                ('BS', models.SmallIntegerField(blank=True, null=True, verbose_name='Blown Saves')),
                ('IP', models.FloatField(blank=True, null=True, verbose_name='Innings Pitched')),
                ('TBF', models.SmallIntegerField(blank=True, null=True, verbose_name='Total Batters Faced')),
                ('H', models.SmallIntegerField(blank=True, null=True, verbose_name='Hits Allowed')),
                ('R', models.SmallIntegerField(blank=True, null=True, verbose_name='Runs Allowed')),
                ('ER', models.SmallIntegerField(blank=True, null=True, verbose_name='Earned Runs Allowed')),
                ('HR', models.SmallIntegerField(blank=True, null=True, verbose_name='Home Runs Allowed')),
                ('BB', models.SmallIntegerField(blank=True, null=True, verbose_name='Walks Allowed')),
                ('IBB', models.SmallIntegerField(blank=True, null=True, verbose_name='Intentional Walks Allowed')),
                ('HBP', models.SmallIntegerField(blank=True, null=True, verbose_name='Hits By Pitch')),
                ('WP', models.SmallIntegerField(blank=True, null=True, verbose_name='Wild Pitches')),
                ('SO', models.SmallIntegerField(blank=True, null=True, verbose_name='Strikeouts')),
                ('fW', models.SmallIntegerField(blank=True, null=True, verbose_name='Fantasy Wins')),
                ('fL', models.SmallIntegerField(blank=True, null=True, verbose_name='Fantasy Losses')),
                ('fERA', models.FloatField(blank=True, null=True, verbose_name='Fantasy Earned Run Average')),
                ('fG', models.SmallIntegerField(blank=True, null=True, verbose_name='Fantasy Games Played')),
                ('fGS', models.SmallIntegerField(blank=True, null=True, verbose_name='Fantasy Games Started')),
                ('fCG', models.SmallIntegerField(blank=True, null=True, verbose_name='Fantasy Complete Games')),
                ('fS', models.SmallIntegerField(blank=True, null=True, verbose_name='Fantasy Shutouts')),
                ('fSV', models.SmallIntegerField(blank=True, null=True, verbose_name='Fantasy Saves')),
                ('fHLD', models.SmallIntegerField(blank=True, null=True, verbose_name='Fantasy Holds')),
                ('fBS', models.SmallIntegerField(blank=True, null=True, verbose_name='Fantasy Blown Saves')),
                ('fIP', models.FloatField(blank=True, null=True, verbose_name='Fantasy Innings Pitched')),
                ('fTBF', models.SmallIntegerField(blank=True, null=True, verbose_name='Fantasy Total Batters Faced')),
                ('fH', models.SmallIntegerField(blank=True, null=True, verbose_name='Fantasy Hits Allowed')),
                ('fR', models.SmallIntegerField(blank=True, null=True, verbose_name='Fantasy Runs Allowed')),
                ('fER', models.SmallIntegerField(blank=True, null=True, verbose_name='Fantasy Earned Runs Allowed')),
                ('fHR', models.SmallIntegerField(blank=True, null=True, verbose_name='Fantasy Home Runs Allowed')),
                ('fBB', models.SmallIntegerField(blank=True, null=True, verbose_name='Fantasy Walks Allowed')),
                ('fIBB', models.SmallIntegerField(blank=True, null=True, verbose_name='Fantasy Intentional Walks Allowed')),
                ('fHBP', models.SmallIntegerField(blank=True, null=True, verbose_name='Fantasy Hits By Pitch')),
                ('fWP', models.SmallIntegerField(blank=True, null=True, verbose_name='Fantasy Wild Pitches')),
                ('fSO', models.SmallIntegerField(blank=True, null=True, verbose_name='Fantasy Strikeouts')),
                ('fTotal', models.SmallIntegerField(blank=True, null=True, verbose_name='Fantasy Total')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Player')),
            ],
            options={
                'verbose_name_plural': 'Pitching Statistics',
                'ordering': ('fTotal', 'id'),
            },
        ),
    ]
