# Generated by Django 3.0.6 on 2020-07-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0011_auto_20200618_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='hittingstatistics',
            name='is_projection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pitchingstatistics',
            name='is_projection',
            field=models.BooleanField(default=False),
        ),
    ]
