# Generated by Django 3.0.6 on 2020-07-22 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0012_auto_20200721_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitchingstatistics',
            name='WHIP',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Walks + Hits/IP'),
        ),
        migrations.AddField(
            model_name='pitchingstatistics',
            name='fWHIP',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Fantasy Walks + Hits/IP'),
        ),
        migrations.AlterField(
            model_name='hittingstatistics',
            name='fBB',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Fantasy Walks'),
        ),
        migrations.AlterField(
            model_name='hittingstatistics',
            name='fCS',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Fantasy Caught Stealing'),
        ),
        migrations.AlterField(
            model_name='hittingstatistics',
            name='fG',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Fantasy Games Played'),
        ),
        migrations.AlterField(
            model_name='hittingstatistics',
            name='fGDP',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Fantasy Grounded into Double Plays'),
        ),
        migrations.AlterField(
            model_name='hittingstatistics',
            name='fHBP',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Fantasy Hit By Pitch'),
        ),
        migrations.AlterField(
            model_name='hittingstatistics',
            name='fIBB',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Fantasy Intentional Walks'),
        ),
        migrations.AlterField(
            model_name='hittingstatistics',
            name='fOBP',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Fantasy On Base Percentage'),
        ),
        migrations.AlterField(
            model_name='hittingstatistics',
            name='fPA',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Fantasy Plate Appearances'),
        ),
        migrations.AlterField(
            model_name='hittingstatistics',
            name='fSF',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Fantasy Sacrifice Flies'),
        ),
        migrations.AlterField(
            model_name='hittingstatistics',
            name='fSH',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Fantasy Sacrifice Hits'),
        ),
        migrations.AlterField(
            model_name='hittingstatistics',
            name='fSLG',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Fantasy Slugging Percentage'),
        ),
        migrations.AlterField(
            model_name='hittingstatistics',
            name='fSO',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Fantasy Strikeouts'),
        ),
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='BB',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Walks Allowed'),
        ),
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='BS',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Blown Saves'),
        ),
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='CG',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Complete Games'),
        ),
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='ER',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Earned Runs Allowed'),
        ),
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='ERA',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Earned Run Average'),
        ),
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='G',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Games Played'),
        ),
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='GS',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Games Started'),
        ),
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='H',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Hits Allowed'),
        ),
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='HBP',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Hits By Pitch'),
        ),
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='HLD',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Holds'),
        ),
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='HR',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Home Runs Allowed'),
        ),
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='IBB',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Intentional Walks Allowed'),
        ),
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='IP',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Innings Pitched'),
        ),
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='L',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Losses'),
        ),
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='R',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Runs Allowed'),
        ),
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='SO',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Strikeouts'),
        ),
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='SV',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Saves'),
        ),
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='ShO',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Shutouts'),
        ),
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='TBF',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Total Batters Faced'),
        ),
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='W',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Wins'),
        ),
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='WP',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Wild Pitches'),
        ),
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='fBB',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Fantasy Walks Allowed'),
        ),
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='fBS',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Fantasy Blown Saves'),
        ),
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='fCG',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Fantasy Complete Games'),
        ),
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='fER',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Fantasy Earned Runs Allowed'),
        ),
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='fERA',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Fantasy Earned Run Average'),
        ),
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='fG',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Fantasy Games Played'),
        ),
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='fGS',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Fantasy Games Started'),
        ),
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='fH',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Fantasy Hits Allowed'),
        ),
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='fHBP',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Fantasy Hits By Pitch'),
        ),
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='fHLD',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Fantasy Holds'),
        ),
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='fHR',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Fantasy Home Runs Allowed'),
        ),
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='fIBB',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Fantasy Intentional Walks Allowed'),
        ),
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='fIP',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Fantasy Innings Pitched'),
        ),
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='fL',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Fantasy Losses'),
        ),
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='fR',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Fantasy Runs Allowed'),
        ),
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='fSO',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Fantasy Strikeouts'),
        ),
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='fSV',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Fantasy Saves'),
        ),
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='fShO',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Fantasy Shutouts'),
        ),
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='fTBF',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Fantasy Total Batters Faced'),
        ),
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='fTotal',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Fantasy Total'),
        ),
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='fW',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Fantasy Wins'),
        ),
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='fWP',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Fantasy Wild Pitches'),
        ),
    ]
