# Generated by Django 2.0.12 on 2020-07-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0013_auto_20200721_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='IP',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5, null=True, verbose_name='Innings Pitched'),
        ),
    ]
