# Generated by Django 3.0.6 on 2021-01-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0014_auto_20200724_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hittingstatistics',
            name='IBB',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Intentional Walks'),
        ),
    ]
