# Generated by Django 3.0.6 on 2021-01-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0016_auto_20210121_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hittingstatistics',
            name='AVG',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Batting Average'),
        ),
        migrations.AlterField(
            model_name='hittingstatistics',
            name='BB',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Walks'),
        ),
        migrations.AlterField(
            model_name='hittingstatistics',
            name='CS',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Caught Stealing'),
        ),
        migrations.AlterField(
            model_name='hittingstatistics',
            name='G',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Games Played'),
        ),
        migrations.AlterField(
            model_name='hittingstatistics',
            name='GDP',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Grounded into Double Plays'),
        ),
        migrations.AlterField(
            model_name='hittingstatistics',
            name='HBP',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Hits By Pitch'),
        ),
        migrations.AlterField(
            model_name='hittingstatistics',
            name='HR',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Home Runs'),
        ),
        migrations.AlterField(
            model_name='hittingstatistics',
            name='OBP',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='On-Base Percentage'),
        ),
        migrations.AlterField(
            model_name='hittingstatistics',
            name='OPS',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='On-Base Plus Slugging'),
        ),
        migrations.AlterField(
            model_name='hittingstatistics',
            name='PA',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Plate Appearances'),
        ),
        migrations.AlterField(
            model_name='hittingstatistics',
            name='R',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Runs Scored'),
        ),
        migrations.AlterField(
            model_name='hittingstatistics',
            name='RBI',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Runs Batted In'),
        ),
        migrations.AlterField(
            model_name='hittingstatistics',
            name='SB',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Stolen Bases'),
        ),
        migrations.AlterField(
            model_name='hittingstatistics',
            name='SF',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Sacrifice Flies'),
        ),
        migrations.AlterField(
            model_name='hittingstatistics',
            name='SH',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Sacrifice Hits'),
        ),
        migrations.AlterField(
            model_name='hittingstatistics',
            name='SLG',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Slugging Percentage'),
        ),
        migrations.AlterField(
            model_name='hittingstatistics',
            name='SO',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Strike Outs'),
        ),
        migrations.AlterField(
            model_name='hittingstatistics',
            name='fAVG',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Fantasy Batting Average'),
        ),
        migrations.AlterField(
            model_name='hittingstatistics',
            name='fBB',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Fantasy Walks'),
        ),
        migrations.AlterField(
            model_name='hittingstatistics',
            name='fCS',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Fantasy Caught Stealing'),
        ),
        migrations.AlterField(
            model_name='hittingstatistics',
            name='fG',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Fantasy Games Played'),
        ),
        migrations.AlterField(
            model_name='hittingstatistics',
            name='fGDP',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Fantasy Grounded into Double Plays'),
        ),
        migrations.AlterField(
            model_name='hittingstatistics',
            name='fHBP',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Fantasy Hit By Pitch'),
        ),
        migrations.AlterField(
            model_name='hittingstatistics',
            name='fHR',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Fantasy Home Runs'),
        ),
        migrations.AlterField(
            model_name='hittingstatistics',
            name='fIBB',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Fantasy Intentional Walks'),
        ),
        migrations.AlterField(
            model_name='hittingstatistics',
            name='fOBP',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Fantasy On Base Percentage'),
        ),
        migrations.AlterField(
            model_name='hittingstatistics',
            name='fOPS',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Fantasy On-Base Plus Slugging'),
        ),
        migrations.AlterField(
            model_name='hittingstatistics',
            name='fPA',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Fantasy Plate Appearances'),
        ),
        migrations.AlterField(
            model_name='hittingstatistics',
            name='fR',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Fantasy Runs Scored'),
        ),
        migrations.AlterField(
            model_name='hittingstatistics',
            name='fRBI',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Fantasy Runs Batted In'),
        ),
        migrations.AlterField(
            model_name='hittingstatistics',
            name='fSB',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Fantasy Stolen Bases'),
        ),
        migrations.AlterField(
            model_name='hittingstatistics',
            name='fSF',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Fantasy Sacrifice Flies'),
        ),
        migrations.AlterField(
            model_name='hittingstatistics',
            name='fSH',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Fantasy Sacrifice Hits'),
        ),
        migrations.AlterField(
            model_name='hittingstatistics',
            name='fSLG',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Fantasy Slugging Percentage'),
        ),
        migrations.AlterField(
            model_name='hittingstatistics',
            name='fSO',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Fantasy Strikeouts'),
        ),
        migrations.AlterField(
            model_name='hittingstatistics',
            name='fTotal',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Fantasy Total'),
        ),
    ]
