# Generated by Django 3.0.6 on 2021-01-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0017_auto_20210121_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hittingstatistics',
            name='SH',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Sacrifice Hits'),
        ),
    ]
