# Generated by Django 3.0.6 on 2021-01-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0018_auto_20210121_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hittingstatistics',
            name='G',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Games Played'),
        ),
    ]
