# Generated by Django 3.0.6 on 2021-01-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0019_auto_20210121_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hittingstatistics',
            name='HR',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Home Runs'),
        ),
        migrations.AlterField(
            model_name='hittingstatistics',
            name='PA',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Plate Appearances'),
        ),
        migrations.AlterField(
            model_name='hittingstatistics',
            name='R',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Runs Scored'),
        ),
        migrations.AlterField(
            model_name='hittingstatistics',
            name='RBI',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Runs Batted In'),
        ),
    ]
