# Generated by Django 3.0.6 on 2021-01-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0020_auto_20210121_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hittingstatistics',
            name='BB',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Walks'),
        ),
    ]
