# Generated by Django 3.0.6 on 2021-01-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0022_auto_20210121_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hittingstatistics',
            name='HBP',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Hits By Pitch'),
        ),
    ]
