# Generated by Django 3.0.6 on 2021-01-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0023_auto_20210121_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hittingstatistics',
            name='SF',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Sacrifice Flies'),
        ),
    ]
