# Generated by Django 3.0.6 on 2021-01-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0027_auto_20210121_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hittingstatistics',
            name='AVG',
            field=models.FloatField(default=0.0, verbose_name='Batting Average'),
        ),
        migrations.AlterField(
            model_name='hittingstatistics',
            name='OBP',
            field=models.FloatField(default=0.0, verbose_name='On-Base Percentage'),
        ),
        migrations.AlterField(
            model_name='hittingstatistics',
            name='SLG',
            field=models.FloatField(default=0.0, verbose_name='Slugging Percentage'),
        ),
    ]
