# Generated by Django 3.0.6 on 2021-01-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0028_auto_20210121_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hittingstatistics',
            name='OPS',
            field=models.FloatField(default=0.0, verbose_name='On-Base Plus Slugging'),
        ),
        migrations.AlterField(
            model_name='hittingstatistics',
            name='fG',
            field=models.SmallIntegerField(default=0, verbose_name='Fantasy Games Played'),
        ),
        migrations.AlterField(
            model_name='hittingstatistics',
            name='fPA',
            field=models.SmallIntegerField(default=0, verbose_name='Fantasy Plate Appearances'),
        ),
    ]
