# Generated by Django 3.0.6 on 2021-01-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0030_auto_20210121_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hittingstatistics',
            name='fBB',
            field=models.SmallIntegerField(default=0, verbose_name='Fantasy Walks'),
        ),
        migrations.AlterField(
            model_name='hittingstatistics',
            name='fIBB',
            field=models.SmallIntegerField(default=0, verbose_name='Fantasy Intentional Walks'),
        ),
        migrations.AlterField(
            model_name='hittingstatistics',
            name='fSO',
            field=models.SmallIntegerField(default=0, verbose_name='Fantasy Strikeouts'),
        ),
    ]
