# Generated by Django 3.0.6 on 2021-01-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0031_auto_20210121_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hittingstatistics',
            name='fHBP',
            field=models.SmallIntegerField(default=0, verbose_name='Fantasy Hit By Pitch'),
        ),
        migrations.AlterField(
            model_name='hittingstatistics',
            name='fSF',
            field=models.SmallIntegerField(default=0, verbose_name='Fantasy Sacrifice Flies'),
        ),
        migrations.AlterField(
            model_name='hittingstatistics',
            name='fSH',
            field=models.SmallIntegerField(default=0, verbose_name='Fantasy Sacrifice Hits'),
        ),
    ]
