# Generated by Django 3.0.6 on 2021-01-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0032_auto_20210121_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hittingstatistics',
            name='fCS',
            field=models.SmallIntegerField(default=0, verbose_name='Fantasy Caught Stealing'),
        ),
        migrations.AlterField(
            model_name='hittingstatistics',
            name='fGDP',
            field=models.SmallIntegerField(default=0, verbose_name='Fantasy Grounded into Double Plays'),
        ),
        migrations.AlterField(
            model_name='hittingstatistics',
            name='fSB',
            field=models.SmallIntegerField(default=0, verbose_name='Fantasy Stolen Bases'),
        ),
    ]
