# Generated by Django 3.0.6 on 2021-01-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0033_auto_20210121_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hittingstatistics',
            name='fAVG',
            field=models.SmallIntegerField(default=0, verbose_name='Fantasy Batting Average'),
        ),
        migrations.AlterField(
            model_name='hittingstatistics',
            name='fOBP',
            field=models.SmallIntegerField(default=0, verbose_name='Fantasy On Base Percentage'),
        ),
        migrations.AlterField(
            model_name='hittingstatistics',
            name='fSLG',
            field=models.SmallIntegerField(default=0, verbose_name='Fantasy Slugging Percentage'),
        ),
    ]
