# Generated by Django 3.0.6 on 2021-01-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0034_auto_20210121_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hittingstatistics',
            name='fOPS',
            field=models.SmallIntegerField(default=0, verbose_name='Fantasy On-Base Plus Slugging'),
        ),
        migrations.AlterField(
            model_name='hittingstatistics',
            name='fTotal',
            field=models.SmallIntegerField(default=0, verbose_name='Fantasy Total'),
        ),
    ]
