# Generated by Django 3.0.6 on 2021-01-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0035_auto_20210121_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='ERA',
            field=models.FloatField(default=0.0, verbose_name='Earned Run Average'),
        ),
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='G',
            field=models.SmallIntegerField(default=0, verbose_name='Games Played'),
        ),
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='L',
            field=models.SmallIntegerField(default=0, verbose_name='Losses'),
        ),
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='W',
            field=models.SmallIntegerField(default=0, verbose_name='Wins'),
        ),
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='WHIP',
            field=models.FloatField(default=0.0, verbose_name='Walks + Hits/IP'),
        ),
    ]
