# Generated by Django 3.0.6 on 2021-01-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0036_auto_20210121_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='CG',
            field=models.SmallIntegerField(default=0, verbose_name='Complete Games'),
        ),
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='GS',
            field=models.SmallIntegerField(default=0, verbose_name='Games Started'),
        ),
    ]
