# Generated by Django 3.0.6 on 2021-01-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0037_auto_20210121_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='HLD',
            field=models.SmallIntegerField(default=0, verbose_name='Holds'),
        ),
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='SV',
            field=models.SmallIntegerField(default=0, verbose_name='Saves'),
        ),
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='ShO',
            field=models.SmallIntegerField(default=0, verbose_name='Shutouts'),
        ),
    ]
