# Generated by Django 3.0.6 on 2021-01-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0038_auto_20210121_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='BS',
            field=models.SmallIntegerField(default=0, verbose_name='Blown Saves'),
        ),
    ]
