# Generated by Django 3.0.6 on 2021-01-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0039_auto_20210121_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='IP',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5, verbose_name='Innings Pitched'),
        ),
    ]
