# Generated by Django 3.0.6 on 2021-01-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0041_auto_20210121_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='ER',
            field=models.SmallIntegerField(default=0, verbose_name='Earned Runs Allowed'),
        ),
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='R',
            field=models.SmallIntegerField(default=0, verbose_name='Runs Allowed'),
        ),
    ]
