# Generated by Django 3.0.6 on 2021-01-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0042_auto_20210121_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='BB',
            field=models.SmallIntegerField(default=0, verbose_name='Walks Allowed'),
        ),
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='HR',
            field=models.SmallIntegerField(default=0, verbose_name='Home Runs Allowed'),
        ),
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='IBB',
            field=models.SmallIntegerField(default=0, verbose_name='Intentional Walks Allowed'),
        ),
    ]
