# Generated by Django 3.0.6 on 2021-01-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0043_auto_20210121_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='HBP',
            field=models.SmallIntegerField(default=0, verbose_name='Hits By Pitch'),
        ),
    ]
