# Generated by Django 3.0.6 on 2021-01-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0044_auto_20210121_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='WP',
            field=models.SmallIntegerField(default=0, verbose_name='Wild Pitches'),
        ),
    ]
