# Generated by Django 3.0.6 on 2021-01-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0045_auto_20210121_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='SO',
            field=models.SmallIntegerField(default=0, verbose_name='Strikeouts'),
        ),
    ]
