# Generated by Django 3.0.6 on 2021-01-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0047_auto_20210121_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='fG',
            field=models.SmallIntegerField(default=0, verbose_name='Fantasy Games Played'),
        ),
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='fGS',
            field=models.SmallIntegerField(default=0, verbose_name='Fantasy Games Started'),
        ),
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='fWHIP',
            field=models.FloatField(default=0.0, verbose_name='Fantasy Walks + Hits/IP'),
        ),
    ]
