# Generated by Django 3.0.6 on 2021-01-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0048_auto_20210121_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='fCG',
            field=models.SmallIntegerField(default=0, verbose_name='Fantasy Complete Games'),
        ),
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='fSV',
            field=models.SmallIntegerField(default=0, verbose_name='Fantasy Saves'),
        ),
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='fShO',
            field=models.SmallIntegerField(default=0, verbose_name='Fantasy Shutouts'),
        ),
    ]
