# Generated by Django 3.0.6 on 2021-01-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0049_auto_20210121_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='fBS',
            field=models.SmallIntegerField(default=0, verbose_name='Fantasy Blown Saves'),
        ),
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='fHLD',
            field=models.SmallIntegerField(default=0, verbose_name='Fantasy Holds'),
        ),
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='fIP',
            field=models.FloatField(default=0.0, verbose_name='Fantasy Innings Pitched'),
        ),
    ]
