# Generated by Django 3.0.6 on 2021-01-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0050_auto_20210121_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='fH',
            field=models.SmallIntegerField(default=0, verbose_name='Fantasy Hits Allowed'),
        ),
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='fR',
            field=models.SmallIntegerField(default=0, verbose_name='Fantasy Runs Allowed'),
        ),
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='fTBF',
            field=models.SmallIntegerField(default=0, verbose_name='Fantasy Total Batters Faced'),
        ),
    ]
