# Generated by Django 3.0.6 on 2021-01-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0051_auto_20210121_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='fBB',
            field=models.SmallIntegerField(default=0, verbose_name='Fantasy Walks Allowed'),
        ),
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='fER',
            field=models.SmallIntegerField(default=0, verbose_name='Fantasy Earned Runs Allowed'),
        ),
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='fHR',
            field=models.SmallIntegerField(default=0, verbose_name='Fantasy Home Runs Allowed'),
        ),
    ]
