# Generated by Django 3.0.6 on 2021-01-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0052_auto_20210121_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='fHBP',
            field=models.SmallIntegerField(default=0, verbose_name='Fantasy Hits By Pitch'),
        ),
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='fIBB',
            field=models.SmallIntegerField(default=0, verbose_name='Fantasy Intentional Walks Allowed'),
        ),
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='fWP',
            field=models.SmallIntegerField(default=0, verbose_name='Fantasy Wild Pitches'),
        ),
    ]
