# Generated by Django 3.0.6 on 2021-01-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0053_auto_20210121_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='fSO',
            field=models.SmallIntegerField(default=0, verbose_name='Fantasy Strikeouts'),
        ),
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='fTotal',
            field=models.SmallIntegerField(default=0, verbose_name='Fantasy Total'),
        ),
    ]
