# Generated by Django 3.0.6 on 2021-01-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0054_auto_20210121_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitchingstatistics',
            name='fK_BB',
            field=models.SmallIntegerField(default=0, verbose_name='Fantasy K/BB'),
        ),
        migrations.AddField(
            model_name='pitchingstatistics',
            name='fSVH',
            field=models.SmallIntegerField(default=0, verbose_name='Fantasy Saves + Holds'),
        ),
    ]
