# Generated by Django 3.0.6 on 2021-01-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0055_auto_20210124_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitchingstatistics',
            name='K_BB',
            field=models.FloatField(default=0, verbose_name='Strikeouts per Walk'),
        ),
        migrations.AddField(
            model_name='pitchingstatistics',
            name='SVH',
            field=models.SmallIntegerField(default=0, verbose_name='Saves + Holds'),
        ),
    ]
