# Generated by Django 3.0.6 on 2021-01-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0057_auto_20210125_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='hittingstatistics',
            name='projection_system',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pitchingstatistics',
            name='projection_system',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
