# Generated by Django 3.0.6 on 2021-01-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0058_auto_20210126_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='ERA',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Earned Run Average'),
        ),
    ]
