# Generated by Django 3.0.6 on 2021-01-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0060_auto_20210127_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitchingstatistics',
            name='fERA',
            field=models.SmallIntegerField(default=0, verbose_name='Fantasy Earned Run Average'),
        ),
    ]
