# Generated by Django 3.2.8 on 2021-12-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0062_auto_20210127_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='fName',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='id',
        ),
        migrations.RemoveField(
            model_name='player',
            name='lName',
        ),
        migrations.AddField(
            model_name='player',
            name='fangraphs_id',
            field=models.CharField(default=0, max_length=10, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
