# Generated by Django 3.0.6 on 2020-05-12 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fstats', '0002_statistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='fName',
            field=models.CharField(max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='player',
            name='lName',
            field=models.CharField(max_length=50, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='fSB',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Fantasy Stolen Bases'),
        ),
    ]
